### ISSUE TITLE
The posibility to zip backups automatically?

### ISSUE THREAD

**Issue by BuyMyMojo** [Futureglobe/Gibu_IssueTracker#1]
**Describe the solution you'd like**
Maybe a check box in the settings to enable zipping of each repo once its backed up or for specific ones?

**Describe alternatives you've considered**
a 7zip version with the settings of 7zip

**Comment by Futureglobe** [comment]
Hello @RelievedStudios ,

Thank you for your feature request.
In general it would be possible to add such a feature.
However, we would prefer to create a general .zip of all repositories within a backup.
This wouldn't affect the performance and would also make it easier for the user to unpack, because he doesn't have to unpack each repo individually.
We are thinking about how to implement this feature.
As soon as it is finished it will be provided with a software update.

Thanks
Your Futureglobe Support Team
